# Generated by Django 3.0.3 on 2020-02-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=50, verbose_name='Студент')),
                ('min_mark', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10, verbose_name='Минимальный балл')),
                ('max_mark', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10, verbose_name='Максимальный балл')),
            ],
        ),
    ]
